### PR TITLE
add Users.GetByID + Update

### PR DESCRIPTION
**Pull request by DrPsychick**
Just adding missing functionality.

I wasn't able to test, because on my M1 keycloak did not come to life with docker-compose. I tried with the bitnami image to no avail.

I hope tests run through without issues 🙃

### CODE REVIEW

**Comment by DrPsychick** [comment]
got the keycloak to work with an amd64 image, test was successful.

**Comment by DrPsychick** [comment]
@zemirco could you merge this? I can also make adjustments if needed.

**Comment by DrPsychick** [comment]
I would have some other suggestions as well and intend to use this library in more cases. Any chance we could join forces and you'd add me to the maintainers? We can have a chat any time.

**Comment by zemirco** [comment]
Thank you for the PR. It's been a weird time the last months. We had our third child and covid also made the whole situation more complicated. Promise to be a better maintainer in the future 😄 

We're currently on holiday but will test and merge as soon as we're back. Hopefully next week!

btw I also made the docker images work on my MacBook but forgot how :) It was about checking out a repo and then checking out a dedicated branch and building from source. Could you also update the README.md where you describe this process?

**Comment by zemirco** [comment]
One thing I noticed. Could you please add dedicated tests for each method? Right now you're testing both methods in a single test. Sometimes this might sound cumbersome but it's nice to have dedicated tests for each method and not mix multiple methods in a single test.

**Comment by DrPsychick** [comment]
no problem @zemirco , fixed.

**Comment by zemirco** [comment]
good job! thank you

**Pull request merged**
